version: "3.9"
services:
  zhaopin-captcha-server:
    build:
      context: ../../src/main/captcha
      dockerfile: Dockerfile

    environment:
      - launchMethod=remote
      - browserWSEndpoint=ws://browserless:3000/
    ports:
      - "9100:9000"
    depends_on:
      - browserless
    restart: always

  zhaopin-extractor-server:
    build:
      context: ../../
      dockerfile: src/main/extractorServer/Dockerfile
    environment:
      - CAPTCHA_SERVER=http://zhaopin-captcha-server:9000
      - PYTHONPATH=.
    ports:
      - "9500:9500"
    command: [ "python", "./src/main/extractorServer/server.py" ]
    depends_on:
      - zhaopin-captcha-server
    restart: always

  browserless:
    image: browserless/chrome:latest
    ports:
      - "8000:3000"
    restart: always